--Q1. What is the total revenue generated by male vs. female customers?
select sum(purchase_amount) as total_revenue,gender from cus_b 
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, discount_applied,sum(purchase_amount) from cus_b 
where discount_applied='Yes'
group by customer_id,discount_applied
having sum(purchase_amount)>(select avg(purchase_amount) from cus_b)
order by sum(purchase_amount) desc

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,avg(review_rating) from cus_b 
group by item_purchased
order by avg(review_rating) desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type , avg(purchase_amount) from cus_b
where shipping_type in ('Standard','Express')
group by shipping_type
--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status, avg(purchase_amount),sum(purchase_amount) from cus_b
group by subscription_status

 